-- MySQL Script generated by MySQL Workbench
-- Wed Nov 12 16:55:48 2025
-- Model: New Model    Version: 1.0

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema temp-node_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema temp-node_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `temp-node_db` DEFAULT CHARACTER SET utf8 ;
USE `temp-node_db` ;

-- -----------------------------------------------------
-- Table `temp-node_db`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `temp-node_db`.`recipe` (
  `recipe_id` INT NOT NULL AUTO_INCREMENT,
  `flavor` VARCHAR(30) NOT NULL,
  `type` VARCHAR(30) NOT NULL,
  `time` TIME NOT NULL,
  PRIMARY KEY (`recipe_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `temp-node_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `temp-node_db`.`user` (
  `username` VARCHAR(25) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `temp-node_db`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `temp-node_db`.`favorite` (
  `username` VARCHAR(25) NOT NULL,
  `recipe_id` INT NOT NULL,
  PRIMARY KEY (`username`, `recipe_id`),
  INDEX `favorite-fk-recipe_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `favorite-fk-recipe`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `temp-node_db`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `favorite-fk-user`
    FOREIGN KEY (`username`)
    REFERENCES `temp-node_db`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `temp-node_db`.`common_allergens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `temp-node_db`.`common_allergens` (
  `recipe_id` INT NOT NULL,
  `allergen` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`recipe_id`, `allergen`),
  CONSTRAINT `common_allergens-fk-recipe`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `temp-node_db`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `temp-node_db`.`recipe_line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `temp-node_db`.`recipe_line` (
  `line_id` INT NOT NULL AUTO_INCREMENT,
  `recipe_id` INT NOT NULL,
  `line` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`line_id`, `recipe_id`),
  INDEX `recipe_line_fk_recipe_idx` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `recipe_line-fk-recipe`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `temp-node_db`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;